# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: bawejakunal # jekyll-seo-tag > Owners twitter username

author: bawejakunal # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Kunal Baweja # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/bawejakunal
    - https://www.facebook.com/kunal.baweja
    - https://www.linkedin.com/in/kunal-baweja
    - https://plus.google.com/+KunalBaweja
    - https://github.com/bawejakunal

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Answers to What When Why & How" # The post list page content
    feature_text: |
      ## What When How & Why ?
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Kunal Baweja" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/placeholder-logo.svg" # Site logo, also used in jekyll-seo-tag
description:
  "Hi I am Kunal Baweja, thanks for stopping by my website, hope you like it here :) I am a graduate student in computer science, interested in working on distributed systems and programming in general. If you like my work, feel free to drop me a message !"

# Site description and default description, also used in jekyll-seo-tag
url: "" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/bawejakunal/bawejakunal.github.io"
email: "bawejakunal15@gmail.com"
disqus: "alembic-1"
avatarurl: "https://avatars0.githubusercontent.com/u/4623624" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/

navigation_footer:
  Inspired by David Darnes: https://darn.es

social_links:
  Twitter: https://twitter.com/bawejakunal
  LinkedIn: https://www.linkedin.com/in/kunal-baweja
  GooglePlus: https://plus.google.com/+KunalBaweja
  GitHub: https://github.com/bawejakunal
