# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- github-pages

# 3. Gem settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: bawejakunal # jekyll-seo-tag > Owners twitter username

author: Kunal Baweja # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Kunal Baweja # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/bawejakunal
    - https://www.facebook.com/kunal.baweja
    - https://www.linkedin.com/in/kunal-baweja
    - https://plus.google.com/+KunalBaweja
    - https://github.com/bawejakunal
    - https://www.flickr.com/photos/bawejakunal/

error_mode: strict
highlighter: rouge

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My views on life universe and everything beyond"
    feature_text: |
      <h2 class="highlighted">What When How & Why ?</h2>
    feature_image: "/assets/blog.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/kunal-logo.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/blog.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Kunal Baweja" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/kunal-logo.png" # Site logo, also used in jekyll-seo-tag

# Site description and default description, also used in jekyll-seo-tag
url: "https://bawejakunal.github.io" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/bawejakunal/bawejakunal.github.io"
email: "bawejakunal15@gmail.com"
disqus: "bawejakunal-github-io"
avatarurl: "https://avatars0.githubusercontent.com/u/4623624" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Blog: /blog/

navigation_footer:
  Theme by David Darnes: https://darn.es

social_links:
  github:     https://github.com/bawejakunal
  linkedin:   https://www.linkedin.com/in/kunal-baweja
  twitter:    https://twitter.com/bawejakunal
  facebook:   https://fb.com/kunal.baweja
  flickr:     https://www.flickr.com/photos/bawejakunal/
  googleplus: https://plus.google.com/+KunalBaweja
